# Generated by Django 4.0.6 on 2022-07-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('headline', models.TextField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, default='work-1.jpg', null=True, upload_to='')),
                ('body', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('github', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='base.tag')),
            ],
        ),
    ]
