# Generated by Django 4.0.6 on 2022-07-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='work-1.jpg', null=True, upload_to='img/'),
        ),
    ]
