# Generated by Django 4.0.6 on 2022-08-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_project_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hosted_at',
            field=models.URLField(blank=True, null=True),
        ),
    ]
